deploy zookeeper to more than one server

diff --git a/app/zookeeper b/app/zookeeper
--- a/app/zookeeper
+++ b/app/zookeeper
@@ -53,20 +53,21 @@ cdepl_app_zookeeper_init()
 ##
 cdepl_app_zookeeper_start()
 {
-	local node=$1
-	local port=$2
+	local node_range_start=$1
+	local node_range_end=$2
+	local port=$3
 
-	local logfile=${__ZOOKEEPER_OUT_PATH}/node${node}${__ZOOKEEPER_LOG_FILE_POSTFIX}
+	if [ "$node_range_end" ]; then
+		local pids=""
 
-	util_log "[$node][zookeeper] Starting, logfile: $logfile"
+		for node in $(seq "$node_range_start" "$node_range_end"); do
+			__cdepl_app_zookeeper_start "$node" "$port" &
+			pids="$pids $!"
+		done
 
-	cdepl_cluster_node_cmd "$node" "mkdir -p $__ZOOKEEPER_OUT_PATH"
-	# Go to zookeeper out dir before execution to get all output, zookeeper
-	# data dir if relative path and zookeeper.out folder in the same dir
-	cdepl_cluster_node_cmd "$node" "sed -i -e \"s/clientPort=[0-9]*/clientPort=$port/g\" \"${__ZOOKEEPER_PATH}/conf/zoo.cfg\" && cd ${__ZOOKEEPER_OUT_PATH} && ${__ZOOKEEPER_PATH}/bin/zkServer.sh start ${__ZOOKEEPER_PATH}/conf/zoo.cfg >> $logfile 2>&1" "$__ZOOKEEPER_REQUIRED_ENVIRONMENT"
-
-	if [ "$?" != "0" ]; then
-		util_log_error_and_exit "[$node][zookeeper] Starting failed, also check logfile $logfile"
+		wait $pids
+	else
+		__cdepl_app_zookeeper_start "$node_range_start" "$port"
 	fi
 }
 
@@ -95,6 +96,68 @@ cdepl_app_zookeeper_remove()
 ##
 cdepl_app_zookeeper_wait_started()
 {
+	local node_range_start=$1
+	local node_range_end=$2
+
+	if [ "$node_range_end" ]; then
+		local pids=""
+
+		for node in $(seq "$node_range_start" "$node_range_end"); do
+			__cdepl_app_zookeeper_wait_started "$node" &
+			pids="$pids $!"
+		done
+
+		wait $pids
+	else
+		__cdepl_app_zookeeper_wait_started "$node_range_start"
+	fi
+}
+
+##
+# Cleanup any still running or remaining/crashed instances on the target node
+#
+# $1 Target node id (or start node id of range if second parameter provided)
+# $2 Optional: Node id range end (including) and first parameter is interpreted
+#    as range start (including)
+##
+cdepl_app_zookeeper_cleanup()
+{
+	local node_range_start=$1
+	local node_range_end=$2
+
+	if [ "$node_range_end" ]; then
+		local pids=""
+
+		for node in $(seq "$node_range_start" "$node_range_end"); do
+			__cdepl_app_zookeeper_cleanup "$node" &
+			pids="$pids $!"
+		done
+
+		wait $pids
+	else
+		__cdepl_app_zookeeper_cleanup "$node_range_start"
+	fi
+}
+
+__cdepl_app_zookeeper_start() {
+	local node=$1
+	local port=$2
+
+	local logfile=${__ZOOKEEPER_OUT_PATH}/node${node}${__ZOOKEEPER_LOG_FILE_POSTFIX}
+
+	util_log "[$node][zookeeper] Starting, logfile: $logfile"
+
+	cdepl_cluster_node_cmd "$node" "mkdir -p $__ZOOKEEPER_OUT_PATH"
+	# Go to zookeeper out dir before execution to get all output, zookeeper
+	# data dir if relative path and zookeeper.out folder in the same dir
+	cdepl_cluster_node_cmd "$node" "sed -i -e \"s/clientPort=[0-9]*/clientPort=$port/g\" \"${__ZOOKEEPER_PATH}/conf/zoo.cfg\" && cd ${__ZOOKEEPER_OUT_PATH} && ${__ZOOKEEPER_PATH}/bin/zkServer.sh start ${__ZOOKEEPER_PATH}/conf/zoo.cfg >> $logfile 2>&1" "$__ZOOKEEPER_REQUIRED_ENVIRONMENT"
+
+	if [ "$?" != "0" ]; then
+		util_log_error_and_exit "[$node][zookeeper] Starting failed, also check logfile $logfile"
+	fi
+}
+
+__cdepl_app_zookeeper_wait_started() {
 	local node=$1
 
 	local logfile=${__ZOOKEEPER_OUT_PATH}/node${node}${__ZOOKEEPER_LOG_FILE_POSTFIX}
@@ -131,32 +194,6 @@ cdepl_app_zookeeper_wait_started()
 
 		sleep 1.0
 	done
-}
-
-##
-# Cleanup any still running or remaining/crashed instances on the target node
-#
-# $1 Target node id (or start node id of range if second parameter provided)
-# $2 Optional: Node id range end (including) and first parameter is interpreted
-#    as range start (including)
-##
-cdepl_app_zookeeper_cleanup()
-{
-	local node_range_start=$1
-	local node_range_end=$2
-
-	if [ "$node_range_end" ]; then
-		local pids=""
-
-		for node in $(seq "$node_range_start" "$node_range_end"); do
-			__cdepl_app_zookeeper_cleanup "$node" &
-			pids="$pids $!"
-		done
-
-		wait $pids
-	else
-		__cdepl_app_zookeeper_cleanup "$node_range_start"
-	fi
 }
 
 __cdepl_app_zookeeper_get_instance_running_pid()
